import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
import { DeviceProvider } from "@/context/DeviceContext";
import ThemeRegistry from "@/components/ThemeRegistry/ThemeRegistry";
import { LocaleProvider } from "@/context/LocaleContext";
import { IntlProvider } from "@/components/providers/IntlProvider";
import { DateFormatProvider } from "@/context/DateFormatContext";
import { CallProvider } from "@/context/CallContext";
import { IncomingCallModal } from "@/components/modals/IncomingCallModal";
import { ActiveCallModal } from "@/components/modals/ActiveCallModal";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LocaleProvider>
          <IntlProvider>
            <DateFormatProvider>
              <ThemeRegistry>
                <DeviceProvider>
                  <AuthProvider>
                    <CallProvider>
                      {children}
                      <IncomingCallModal />
                      <ActiveCallModal />
                    </CallProvider>
                  </AuthProvider>
                </DeviceProvider>
              </ThemeRegistry>
            </DateFormatProvider>
          </IntlProvider>
        </LocaleProvider>
      </body>
    </html>
  );
}

